version: '2'
services:
 mongodb-replica:
    build: ./mongodb
    ports:
     - "27017:27017"
     - "27018:27018"
     - "27019:27019"
  elastic:
    build: ./elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
 es_slave:
    build: ./es_slave
    ports:
     - "9301:9301"
     - "9201:9201"
    links:
     - elastic
    depends_on: 
     - elastic
 graylog2:
    build: ./graylog2-2.1.2
    ports:
     - "80:80"
     - "9350:9350"
     - "12201:12201"
     - "12201:12201/udp"
     - "12900:12900"
    links:
     - elastic
     - mongodb
    depends_on: 
     - mongodb
