version: '2'
services:
  java:
    build: ./java
    image: java-jre:1.8
  mongodb:
    image: mongo:2.6
    container_name: mongodb
    networks:
        graylog:
    ports:
     - "27017:27017"
     - "28574:28574"
  elastic:
    image: elasticsearch
    build: ./elasticsearch
    container_name: elastic
    networks:
        graylog:
    ports:
     - "9200:9200"
     - "9300:9300"
    depends_on:
     - java
  es_slave:
    build: ./es_slave
    container_name: es-slave
    ports:
     - "9301:9301"
     - "9201:9201"
    links:
     - elastic
    networks:
        graylog:
    depends_on: 
     - java
     - elastic
  graylog2:
    build: ./graylog
    image: graylog
    privileged: true
    networks:
        graylog:
    ports:
     - "9350:9350"
     - "12201:12201"
     - "12201:12201/udp"
     - "12900:12900"
    links:
     - elastic
     - mongodb
    depends_on: 
     - java
     - mongodb
networks:
  graylog:
